Kong Terraform integration Test
paion-data/immutable-infrastructure-as-a-service pull request #41
Opened 2024-05-07 09:45 UTC by qing-wq

[//]: # (Copyright 2024 Paion Data)

[//]: # (Licensed under the Apache License, Version 2.0 &#40;the "License"&#41;;)
[//]: # (you may not use this file except in compliance with the License.)
[//]: # (You may obtain a copy of the License at)

[//]: # (http://www.apache.org/licenses/LICENSE-2.0)

[//]: # (Unless required by applicable law or agreed to in writing, software)
[//]: # (distributed under the License is distributed on an "AS IS" BASIS,)
[//]: # (WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.)
[//]: # (See the License for the specific language governing permissions and)
[//]: # (limitations under the License.)

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

- [ ] Test
- [ ] Self-review
- [ ] Documentation

2024-05-14 01:06 UTC, QubitPi requested changes
- `testing`/`test` 文件夹的名字不太好区别，建议改成 [`harness`](https://en.wikipedia.org/wiki/Test_harness)/'test'
- `sleep` 等待逻辑我没有去审核
- 目前来说，写的很好 <img src="https://github.com/QubitPi/QubitPi/blob/master/code-reviews/%E7%BA%B3%E8%A5%BF%E5%A6%B2/8%E5%A5%BD.gif?raw=true" width="60px" />

2024-05-14 02:07 UTC, qing-wq commented on tests/kong-api-gateway/instances/tests/kong.tftest.hcl
> +}
ready的作用是隐式执行`command = apply`，再由tests_kong模块对已启动的服务进行验证

2024-05-14 02:12 UTC, qing-wq commented on hashicorp/kong-api-gateway/instances/ali-kong.tf
> +// TODO: image_name 多版本会有问题  修改成image_id
阿里云image也有`tag`的概念，也就是说`image_name`不一定是唯一的，可能获取到的`image_name`不是我们想要的目前的想法是在CI/CD中通过output可以将`image_id`传递给terraform

2024-05-16 01:01 UTC, QubitPi requested changes

2024-05-16 03:20 UTC, qing-wq commented on tests/kong-api-gateway/scripts/wait-on.sh
> +fi
`wait-on`脚本的作用是30s内每隔1s访问一次3000端口，如果请求状态码为200则视为启动成功，超时则返回错误状态码，前端项目每次大概需要10s的时间才能启动，也可能更久

2024-05-17 00:58 UTC, QubitPi requested changes

2024-05-17 02:30 UTC, qing-wq commented on .github/workflows/ci-cd.yml
> +        uses: fernandrone/linelint@0.0.4
![image](https://github.com/paion-data/immutable-infrastructure-as-a-service/assets/93132738/1ae07bd0-386a-4ee2-bcd4-6fa4f4b75f67)
文档中的脚本已经不可用，`fernandrone/linelint@0.0.4`是github action支持的方式

2024-07-10 07:44 UTC, closed without merging